version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch